### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by TomMalfrere** [Wizzard72/Domoticz-Unifi-Presence#34]
I'm getting the following error:
2022-05-28 16:34:49.090 Error: Unifi controller: _plugin.onHeartbeat()
2022-05-28 16:34:49.091 Error: Unifi controller: File "/home/pi/domoticz/plugins/Domoticz-Unifi-Presence.backup/plugin.py", line 499, in onHeartbeat
2022-05-28 16:34:49.091 Error: Unifi controller: if self.Matrix[0][3] == "On":
2022-05-28 16:34:49.091 Error: Unifi controller: IndexError: string index out of range
2022-05-28 16:34:51.570 RFXCOM: Temp + Humidity (kelder)
2022-05-28 16:34:54.102 Error: Unifi controller: Call to function 'onHeartbeat' failed, exception details:
2022-05-28 16:34:54.104 Error: Unifi controller: Traceback (most recent call last):
2022-05-28 16:34:54.104 Error: Unifi controller: File "/home/pi/domoticz/plugins/Domoticz-Unifi-Presence.backup/plugin.py", line 1106, in onHeartbeat
2022-05-28 16:34:54.104 Error: Unifi controller: _plugin.onHeartbeat()
2022-05-28 16:34:54.104 Error: Unifi controller: File "/home/pi/domoticz/plugins/Domoticz-Unifi-Presence.backup/plugin.py", line 499, in onHeartbeat
2022-05-28 16:34:54.104 Error: Unifi controller: if self.Matrix[0][3] == "On":
2022-05-28 16:34:54.104 Error: Unifi controller: IndexError: string index out of range
2022-05-28 16:34:59.067 Error: Unifi controller: Call to function 'onHeartbeat' failed, exception details:

Can somebody help me out here?

**Comment by Wizzard72** [comment]
Can you share your plugin settings

**Comment by TomMalfrere** [comment]
![image](https://user-images.githubusercontent.com/35227756/170891476-365f50fd-8a4b-479b-93af-0d3a542dbf00.png)

**Comment by Wizzard72** [comment]
I have just released a new version. Can you update and share the whole plugin log?

**Comment by TomMalfrere** [comment]
I have 2 problems:
1) I tried a "git pull" but the version remains at 3.0.5. I'm not getting 3.0.6...
2) where can I find the plugin log?

**Comment by TomMalfrere** [comment]
OK, I've got 3.0.6

**Comment by TomMalfrere** [comment]
2022-06-01 12:02:26.223 Unifi controller: Worker thread started.
2022-06-01 12:02:26.223 Status: Unifi controller: Entering work loop.
2022-06-01 12:02:26.224 Status: Unifi controller: Started.
2022-06-01 12:02:28.140 Unifi controller: Debug logging mask set to: NONE
2022-06-01 12:02:28.141 Unifi controller: setVersionCheck - Plugin allowed to start (triggered by: onStart)
2022-06-01 12:02:28.143 Unifi controller: onStart: Found devicestable.txt file
2022-06-01 12:02:28.143 Unifi controller: Number of icons loaded = 3
2022-06-01 12:02:28.144 Unifi controller: onStart: Items = UnifiPresenceAnyone
2022-06-01 12:02:28.144 Unifi controller: onStart: Icon 101 Name = UnifiPresence
2022-06-01 12:02:28.144 Unifi controller: onStart: Items = UnifiPresenceOverride
2022-06-01 12:02:28.144 Unifi controller: onStart: Icon 102 Name = UnifiPresence
2022-06-01 12:02:28.144 Unifi controller: onStart: Items = UnifiPresenceDevice
2022-06-01 12:02:28.144 Unifi controller: onStart: Icon 103 Name = UnifiPresence
2022-06-01 12:02:28.130 Status: Unifi controller: Initialized version 3.0.6, author 'Wizzard72'
2022-06-01 12:02:29.592 Unifi controller: login: Login successful into Unifi Controller
2022-06-01 12:02:29.795 Unifi controller: detect Unifi Devices: Found Unifi Device: UniFi AP-AC-Lite (U7LT)
2022-06-01 12:02:29.800 Unifi controller: detect Unifi Devices: Found Unifi Device: Unifi Switch Lite 16 PoE (USL16LP)
2022-06-01 12:02:29.806 Unifi controller: detect Unifi Devices: Found Unifi Device: UniFi AP-AC-LR (U7LR)
2022-06-01 12:02:29.807 Unifi controller: create_devices: Plugin Name = Unifi controller
2022-06-01 12:02:29.807 Unifi controller: create_devices: Found phone to monitor from configuration = Tom=a2:14:65:0d:0c:2b
2022-06-01 12:02:29.807 Unifi controller: UpdateDevice: Update (sValue): On --> Off (Unifi controller - Tom) Image=None
2022-06-01 12:02:29.838 Unifi controller: create_devices: Found phone to monitor from configuration = Veerle=f6:d0:10:18:37:36
2022-06-01 12:02:29.838 Unifi controller: UpdateDevice: Update (sValue): Off --> On (Unifi controller - Veerle) Image=None
2022-06-01 12:02:29.867 Unifi controller: UpdateDevice: Update (sValue): On --> Off (Unifi controller - Veerle) Image=None
2022-06-01 12:02:29.900 Unifi controller: onStart: Phone Naam = OverRide | 00:00:00:00:00:00 | 255 | Off | No | No
2022-06-01 12:02:29.901 Unifi controller: onStart: Phone Naam = Tom | a2:14:65:0d:0c:2b | 50 | Off | No | No
2022-06-01 12:02:29.901 Unifi controller: onStart: Phone Naam = Veerle | f6:d0:10:18:37:36 | 51 | Off | No | No
2022-06-01 12:02:31.309 Unifi controller: ProcessDevices: Phone 'Tom' connected to the Unifi Controller
2022-06-01 12:02:31.309 Unifi controller: UpdateDevice: Update (sValue): Off --> On (Unifi controller - Tom) Image=None
2022-06-01 12:02:31.356 Unifi controller: ProcessDevices: Total Phones connected = 1

**Comment by Wizzard72** [comment]
This looks good. No errors in the log.

**Comment by TomMalfrere** [comment]
Hi,

I'm afraid the problem is back since 07/07/2022:

2022-07-11 11:44:48.099 Error: Unifi controller: Call to function 'onHeartbeat' failed, exception details:
2022-07-11 11:44:48.100 Error: Unifi controller: Traceback (most recent call last):
2022-07-11 11:44:48.100 Error: Unifi controller: File "/home/pi/domoticz/plugins/Domoticz-Unifi-Presence/plugin.py", line 1110, in onHeartbeat
2022-07-11 11:44:48.100 Error: Unifi controller: _plugin.onHeartbeat()
2022-07-11 11:44:48.100 Error: Unifi controller: File "/home/pi/domoticz/plugins/Domoticz-Unifi-Presence/plugin.py", line 503, in onHeartbeat
2022-07-11 11:44:48.100 Error: Unifi controller: if self.Matrix[0][3] == "On":
2022-07-11 11:44:48.100 Error: Unifi controller: IndexError: string index out of range
